{% set name = "ecmwflibs" %}
{% set version = "0.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ecmwf/ecmwflibs/archive/refs/tags/{{ version }}.tar.gz
  sha256: 5e1e5a665cae9a94d846f7035253ddeb4b15bbb4d2e46cc91ed6975331f4d7bd
  patches:
    - find_conda_libs.diff

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - pip
    - setuptools
    - eccodes
    - magics
  run:
    - python
    - findlibs
    - {{ pin_compatible('eccodes', max_pin='x.x') }}
    - {{ pin_compatible('magics', max_pin='x.x') }}

test:
  imports:
    - ecmwflibs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ecmwf/ecmwflibs
  summary: Wraps ECMWF tools (experimental)
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE.md

extra:
  recipe-maintainers:
    - isuruf
    - timkpaine
